/**:
  ros__parameters:
    environments: ["cx_file_load"]
    cx_file_load:
      plugins: ["files"]
      watch: ["facts", "rules"]

    files:
      plugin: "cx::FileLoadPlugin"
      # When specifying relative paths, look at the share directories of the listed packages to resolve them.
      # Attempts to resolve the relative paths in order of the listed packages
      # Defaults to an empty list
      pkg_share_dirs: ["cx_bringup"]
      # Specify files to load using CLIPS load* command when the plugin is loaded.
      # Supports absolute paths or relative paths using the share directories specified above.
      # Defaults to an empty list
      load: ["clips/plugin_examples/file-load.clp"]
      # Specify files to load using CLIPS batch* command when the plugin is loaded.
      # Supports absolute paths or relative paths using the share directories specified above.
      # Defaults to an empty list
      batch: ["clips/plugin_examples/file-load-batch.clp"]
      # Specify files to load using CLIPS batch* command when the plugin is unloaded.
      # This may be used to clean up all loaded content to enable dynamic reloading of plugins at runtime.
      # Supports absolute paths or relative paths using the share directories specified above.
      # Defaults to an empty list
      cleanup_batch: ["clips/plugin_examples/file-load-cleanup-batch.clp"]
