/**:
  ros__parameters:
    environments: ["cx_set_bool_srvs"]
    cx_set_bool_srvs:
      plugins: ["executive", "set_bool", "files"]
      log_clips_to_file: true
      watch: ["facts", "rules"]

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    set_bool:
      plugin: "cx::CXStdSrvsSetBoolPlugin"
    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_bringup"]
      load: [
        "clips/plugin_examples/set-bool-srv.clp"]
