/**:
  ros__parameters:
    environments: ["cx_string_msg"]
    cx_string_msg:
      plugins: ["executive", "string_msg", "files"]
      log_clips_to_file: true
      watch: ["facts", "rules"]

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    string_msg:
      plugin: "cx::CXStdMsgsStringPlugin"
    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_bringup"]
      load: [
        "clips/plugin_examples/string-msg.clp"]
