/**:
  ros__parameters:
    environments: ["cx_executive"]
    cx_executive:
      plugins: ["executive", "files"]
      log_clips_to_file: true
      watch: ["facts", "rules"]

    executive:
      plugin: "cx::ExecutivePlugin"
      # Publish an empty messae with each agenda refresh.
      # Mainly useful for debug purposes to observe true refresh rate.
      # Defaults to false
      publish_on_refresh: false
      # With each iteration, insert the latest ros time into the CLIPS environment.
      # Defaults to true
      assert_time: true
      # Rate with which the environments should run in hz.
      # Note that this is only an upper bound, as it lets all environment
      # run until the Agenda is empty.
      # Defaults to 10
      refresh_rate: 10
    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_bringup"]
      load: [
        "clips/plugin_examples/executive.clp"]
