/**:
  ros__parameters:
    environments: ["cx_fibonacci_action"]
    cx_fibonacci_action:
      plugins: ["executive", "fibonacci", "files"]
      log_clips_to_file: true
      watch: ["facts", "rules"]

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    fibonacci:
      plugin: "cx::CXExampleInterfacesFibonacciPlugin"
    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_bringup"]
      load: [
        "clips/plugin_examples/fibonacci-action.clp"]
