/**:
  ros__parameters:
    environments: ["cx_protobuf"]
    cx_protobuf:
      plugins: ["executive", "protobuf", "files"]
      log_clips_to_file: true
      watch: ["facts", "rules"]

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 1
    protobuf:
      plugin: "cx::ProtobufPlugin"
      # When specifying relative paths, look at the share directories of the listed packages to resolve them.
      # Attempts to resolve the relative paths in order of the listed packages
      # Defaults to an empty list
      pkg_share_dirs: ["cx_bringup"]
      # Specify directories to look for protobuf messages.
      # Supports absolute paths or relative paths using the share directories specified above.
      # Defaults to an empty list
      proto_paths: ["proto/cx_bringup"]

    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_bringup"]
      load: [
        "clips/plugin_examples/protobuf.clp"]
